grammar LogicC;

@node (
return Boolean;
default false;
)

a       :
    b aPoint;

aPoint  :
    OR b aPoint
    | EPS;

b       :
    c bPoint;

bPoint  :
    XOR c bPoint
    | EPS ;

c       :
    d cPoint ;

cPoint  :
    AND d cPoint
    | EPS;

d       :
    NOT e
    | e;

e       :
    LB a RB
    | VAR;

AND : '\\&';
OR : '\\|';
XOR : '\\^';
NOT : '\\!';
LB      : '\\(' ;
RB      : '\\)' ;
VAR    : '[a-zA-Z]+';